apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stirling-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure

spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - stirling.bauerhouse.net
  rules:
    - host: stirling.bauerhouse.net
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: stirling-pdf
                port:
                  number: 8080
